FROM java:8
VOLUME /tmp
ADD target/canteen_plan_service-1.0.0.jar canteen_plan_service-1.0.0.jar
RUN bash -c 'touch /canteen_plan_service-1.0.0.jar'
EXPOSE 8085
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/canteen_plan_service-1.0.0.jar"]