FROM java:8
VOLUME /tmp
ADD target/feed_service-1.0.0.jar feed_service-1.0.0.jar
RUN bash -c 'touch /feed_service-1.0.0.jar'
EXPOSE 8086
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/feed_service-1.0.0.jar"]