version: "3"
services:

  splanrestapi:
    build: ./splanservice
    restart: always 
    ports:
    - "8080:8080"

  #subrestapi:
    #build: ./subscriptionservice
    #ports:
    #  - "8081:8081"

  #subredis:
    #image: "redis"
    #ports:
    #  - "6379:6379"

  userrestapi:
    build: ./benutzerservice
    restart: always 
    ports:
      - "8082:8082"

  meetingrestapi:
    build: ./meeting_service
    restart: always 
    ports:
      - "8083:8083"

  semesterdatesrestapi:
    build: ./semester_dates_service
    restart: always 
    ports:
      - "8084:8084"

  canteenrestapi:
    build: ./canteen_plan_service
    restart: always 
    ports:
      - "8085:8085"

  feedrestapi:
    build: ./feed_service
    restart: always 
    ports:
      - "8086:8086"
    links: 
      - canteenrestapi
      - semesterdatesrestapi
      - meetingrestapi